[package]
name = "SaBeDin_crm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.4"
tokio = { version = "1.0", features = ["full"] }
log = "0.4.20"
serde = { version = "1.0.196", features = ["derive"] }
chrono = "0.4.33"
openssl = { version = "0.10", features = ["vendored"] }
kafka = "0.10.0"